services:
  frontend:
    container_name: client
    image: nettune123/docker-course-frontend:1.0
    ports:
      - 80:80
    networks:
      - internal
    environment:
      - NODE_PATH=/app/src
    depends_on:
      - backend

  backend:
    container_name: server
    image: nettune123/docker-course-backend:1.0
    ports:
      - 4000:4000
    networks:
      - internal
    env_file:
    - ./nodejs/.env
    environment:
      - NODE_PATH=production
    depends_on:
      - db
  db:
    container_name: database
    image: nettune123/mongo:1.0
    # environment:
    #   MONGO_INITDB_DATABASE: node-app
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - internal

networks:
  internal:

volumes:
  mongo_data:
  mongo_config:
